# Generated by Django 6.0.1 on 2026-01-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('business', 'Business')], max_length=10),
        ),
    ]
