# Generated by Django 6.0.1 on 2026-01-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0004_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetail',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
